baseURL = 'https://yuncheolkim.github.io/'
languageCode = 'en-us'
title = '骑驴找马'
theme = "navsite"
canonifyURLs = true

[[menu.main]]
name = "导航"
url = "/links/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 4


[[menu.main]]
name = "提交问题"
url = "https://github.com/yuncheolkim/yuncheolkim.github.io/issues/new"
weight = 6
