baseURL = 'https://yuncheolkim.github.io/'
languageCode = 'en-us'
title = '骑驴找马'
theme = "navsite"
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.attribute]
      block = true
      title = true

[[menu.main]]
name = "导航"
url = "/links/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 4

