baseURL = 'https://www.qilvzm.com/'
languageCode = 'zh-cn'
title = '骑驴找马-人生导航'
theme = "navsite"
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.attribute]
      block = true
      title = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[[menu.main]]
name = "导航"
url = "/links/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 4

